const questions = [
    { id: 1, category: "revisao", text: "Antes de enviar um texto, você releu cada frase para verificar se disse exatamente o que pensou?" },
    { id: 2, category: "revisao", text: "Você apaga e reescreve palavras inteiras buscando o impacto emocional certo?" },
    { id: 3, category: "revisao", text: "Após terminar de escrever, você relê o texto inteiro como se fosse um leitor pela primeira vez?" },
    { id: 4, category: "revisao", text: "Você reordena parágrafos inteiros para melhorar o fluxo da ideia?" },
    { id: 5, category: "revisao", text: "Antes de considerar um texto 'pronto', você lê em voz alta para sentir se soa natural?" },
    { id: 6, category: "criatividade", text: "Você começa a escrever sem saber exatamente onde vai chegar, deixando a história te guiar?" },
    { id: 7, category: "criatividade", text: "Quando não sabe uma palavra, você inventa uma descrição ao invés de pedir sugestões?" },
    { id: 8, category: "criatividade", text: "Você cria metáforas ou analogias para explicar suas ideias?" },
    { id: 9, category: "criatividade", text: "Você inventa personagens ou situações quando escreve sobre si mesmo?" },
    { id: 10, category: "criatividade", text: "Você adiciona detalhes visuais ou sensoriais para enriquecer seu texto?" },
    { id: 11, category: "autonomia", text: "Antes de pedir ajuda, você tenta encontrar a resposta sozinho, vasculhando sua própria mente?" },
    { id: 12, category: "autonomia", text: "Quando alguém critica seu texto, você considera cada ponto antes de decidir o que manter?" },
    { id: 13, category: "autonomia", text: "Você prefere descobrir as coisas por conta própria antes de buscar ajuda externa?" },
    { id: 14, category: "autonomia", text: "Você toma decisões sozinho sobre como expressar suas ideias, mesmo sem certeza?" },
    { id: 15, category: "autonomia", text: "Você se sente confortável em errar e aprender com os próprios erros?" },
    { id: 16, category: "planejamento", text: "Quando escreve, você imagina quem vai ler e adapta sua linguagem para essa pessoa?" },
    { id: 17, category: "planejamento", text: "Você ajusta o ritmo das frases — curtas para tensão, longas para reflexão — conforme o momento?" },
    { id: 18, category: "planejamento", text: "Você pensa na estrutura do texto antes de começar a escrever?" },
    { id: 19, category: "planejamento", text: "Você organiza suas ideias em tópicos ou mentalmente antes de colocar no papel?" },
    { id: 20, category: "planejamento", text: "Você faz um esboço ou lista do que quer escrever antes de começar?" },
    { id: 21, category: "emocao", text: "Você expressa seus sentimentos abertamente nos textos que escreve?" },
    { id: 22, category: "emocao", text: "Você usa palavras emocionalmente carregadas para criar impacto?" },
    { id: 23, category: "emocao", text: "Você escreve de forma diferente dependendo do tema (mais sério com amigos, mais formal com professores)?" },
    { id: 24, category: "emocao", text: "Você se permite ser vulnerável ao escrever sobre experiências pessoais?" },
    { id: 25, category: "emocao", text: "Você detecta quando uma frase 'não soa certa' emocionalmente e corrige?" },
    { id: 26, category: "ritmo", text: "Você escreve primeiro e edita depois, separando criação de refinamento?" },
    { id: 27, category: "ritmo", text: "Você mantém um fluxo constante de escrita sem interrupções longas?" },
    { id: 28, category: "ritmo", text: "Você digita continuamente sem parar para pensar em cada palavra?" },
    { id: 29, category: "ritmo", text: "Você sente quando o texto 'flui' naturalmente e aproveita esses momentos?" },
    { id: 30, category: "ritmo", text: "Você faz pausas estratégicas para planejar a próxima frase?" },
    { id: 31, category: "vocabulario", text: "Você muda palavras repetitivas por sinônimos mesmo quando está cansado?" },
    { id: 32, category: "vocabulario", text: "Você escolhe palavras não apenas pelo significado, mas pelo som e ritmo que elas criam?" },
    { id: 33, category: "vocabulario", text: "Você busca palavras específicas para capturar exatamente o que sente?" },
    { id: 34, category: "vocabulario", text: "Você experimenta palavras novas que ouviu ou leu recentemente?" },
    { id: 35, category: "vocabulario", text: "Você usa linguagem figurada (metáforas, similes) para enriquecer o texto?" },
    { id: 36, category: "estrutura", text: "Você separa o texto em parágrafos com temas distintos?" },
    { id: 37, category: "estrutura", text: "Você usa conectivos (então, porém, além disso) para ligar as ideias?" },
    { id: 38, category: "estrutura", text: "Você garante que cada parágrafo tenha uma ideia principal clara?" },
    { id: 39, category: "estrutura", text: "Você revisita textos antigos para ver como sua escrita evoluiu?" },
    { id: 40, category: "estrutura", text: "Você mantém uma estrutura consistente em textos similares?" },
    { id: 41, category: "reflexao", text: "Antes de entregar, você se pergunta: 'Isso realmente me representa?'" },
    { id: 42, category: "reflexao", text: "Você escreve para descobrir o que realmente pensa sobre um assunto?" },
    { id: 43, category: "reflexao", text: "Você percebe padrões recurring em sua forma de escrever?" },
    { id: 44, category: "reflexao", text: "Você reflete sobre como suas experiências pessoais influenciam sua escrita?" },
    { id: 45, category: "reflexao", text: "Você se pergunta como seu texto será interpretado pelos outros?" },
    { id: 46, category: "interacao", text: "Você pede feedback específico sobre aspectos que quer melhorar?" },
    { id: 47, category: "interacao", text: "Você mostra seus textos para outras pessoas antes de finalizar?" },
    { id: 48, category: "interacao", text: "Você incorpora sugestões de outras pessoas quando fazem sentido para você?" },
];